"""
Regenerates dashboard/data/*.data.js from each track's learning_tracker.xlsx.

Run this whenever a Tracker sheet or Self-Assessment Checklist changes:

    python dashboard/scripts/generate_data.py

The dashboard reads these as plain <script> includes (not fetch/JSON) so the
HTML files work by double-clicking them open, with no local server needed.
"""

import datetime
import json
import openpyxl

TRACKS = [
    {
        "key": "node",
        "file": "Node/learning_tracker.xlsx",
        "title": "Node -> NestJS",
        "subtitle": "NestJS + TypeScript + TypeORM",
        "accent": "node",
    },
    {
        "key": "angular",
        "file": "Angular/learning_tracker.xlsx",
        "title": "Angular 19",
        "subtitle": "Signals, RxJS, SCSS & i18n",
        "accent": "angular",
    },
    {
        "key": "python",
        "file": "Python/learning_tracker.xlsx",
        "title": "Python",
        "subtitle": "Async, FastAPI, Pydantic & pandas",
        "accent": "python",
    },
]


def cell_str(value):
    if value is None:
        return ""
    if isinstance(value, (datetime.date, datetime.datetime)):
        return value.strftime("%Y-%m-%d")
    return str(value).strip()


def read_tracker(ws):
    concepts = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        phase = cell_str(row[0])
        if not phase:
            break
        concepts.append({
            "phase": phase,
            "id": cell_str(row[1]),
            "concept": cell_str(row[2]),
            "status": cell_str(row[3]) or "Not Started",
            "practiceDone": cell_str(row[4]) == "Yes",
            "selfCheckPassed": cell_str(row[5]) == "Yes",
            "dateStarted": cell_str(row[6]),
            "dateCompleted": cell_str(row[7]),
            "notes": cell_str(row[8]) if len(row) > 8 else "",
        })
    return concepts


def read_checklist(ws):
    items = []
    started = False
    for row in ws.iter_rows(values_only=True):
        first = cell_str(row[0])
        if not started:
            if first == "#":
                started = True
            continue
        if not first:
            break
        items.append({
            "id": first,
            "item": cell_str(row[1]),
            "completed": cell_str(row[2]) == "Yes",
            "date": cell_str(row[3]) if len(row) > 3 else "",
        })
    return items


def main():
    generated_at = datetime.date.today().strftime("%Y-%m-%d")
    for track in TRACKS:
        wb = openpyxl.load_workbook(track["file"], data_only=True)
        data = {
            "key": track["key"],
            "title": track["title"],
            "subtitle": track["subtitle"],
            "accent": track["accent"],
            "generatedAt": generated_at,
            "concepts": read_tracker(wb["Tracker"]),
            "checklist": read_checklist(wb["Self-Assessment Checklist"]),
        }
        out_path = f"dashboard/data/{track['key']}.data.js"
        payload = json.dumps(data, indent=2, ensure_ascii=False)
        js = (
            "// Auto-generated by dashboard/scripts/generate_data.py — do not edit by hand.\n"
            "window.DASHBOARD_DATA = window.DASHBOARD_DATA || {};\n"
            f"window.DASHBOARD_DATA.{track['key']} = {payload};\n"
        )
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(js)
        print(f"wrote {out_path} ({len(data['concepts'])} concepts, {len(data['checklist'])} checklist items)")


if __name__ == "__main__":
    main()
